swagger: '2.0'
basePath: /
paths:
  /data/{id}/{name}:
    parameters:
      - name: id
        in: path
        required: true
        type: integer
      - name: name
        in: path
        required: true
        type: string
    get:
      responses:
        '200':
          description: Data fetched successfully
          schema:
            $ref: '#/definitions/Data'
      summary: Fetches data from PostgreSQL and returns it
      description: Fetches data from PostgreSQL and returns it
      operationId: get_data_resource
      parameters:
        - name: X-Fields
          in: header
          type: string
          format: mask
          description: An optional fields mask
      tags:
        - default
info:
  title: API
  version: '1.0'
produces:
  - application/json
consumes:
  - application/json
tags:
  - name: User Data
    description: data of id,name,age
definitions:
  Data:
    properties:
      data:
        type: array
        items:
          type: string
    type: object
responses:
  ParseError:
    description: When a mask can't be parsed
  MaskError:
    description: When any error occurs on mask
